### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by valientes**
I established a package structure. I made it work, but still I prefer your approval

### CODE REVIEW

**Comment by TomxHWRxWI20C** [comment]
willst du das schon auf den master schieben?

**Review by TomxHWRxWI20C — CHANGES_REQUESTED** [review]
code lgtm
would merge with development

**Comment by valientes** [comment]
Okay, but what good is the master branch then, if we all push it onto dev?

Also, I had to look up "lgtm". First proposition was "literally garbage to me", but I guess you mean the exact opposite which is more common 😅

**Comment by TomxHWRxWI20C** [comment]
Looks Good To Me
xD
Master is only for stable release versions
All methods aren't tested yet :)

**Comment by valientes** [comment]
Yeah, you're right. Guess I'll close this pull request and open another one on dev

**Pull request closed without merging**
